export { default as SWelcome } from './SWelcome'
export { default as SConfirmPhoneNum } from './SConfirmPhoneNum'
export { default as OTP } from './OTP'
export { default as SForgotPassword } from './SForgotPassword'
export { default as MainScreen } from './MainScreen'
export {default as SOrder} from '../screens/MainScreen/SOrder'
export {default as SChat} from '../screens/MainScreen/SChat'
export {default as SGoogleMap} from '../screens/MainScreen/SGoogleMap'